
services:

  nbchat-kb-ocr-1:
    image: 192.168.10.155:7777/nbchat_build_release/nbchat-kb-ocr:2.0
    container_name: nbchat-kb-ocr-1
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    ports:
      - 28081:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/8080'"]
      interval: 5s         # 每 5 秒检测一次
      timeout: 3s          # 检查超时 3 秒
      retries: 5           # 连续 5 次失败才标记为 unhealthy
      start_period: 60s    # 容器启动后等待 10 秒再开始健康检查
    runtime: nvidia
    networks:
      - custom-network

  nbchat-kb-ocr-2:
    image: 192.168.10.155:7777/nbchat_build_release/nbchat-kb-ocr:2.0
    container_name: nbchat-kb-ocr-2
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    ports:
      - 28082:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/8080'"]
      interval: 5s         # 每 5 秒检测一次
      timeout: 3s          # 检查超时 3 秒
      retries: 5           # 连续 5 次失败才标记为 unhealthy
      start_period: 60s    # 容器启动后等待 10 秒再开始健康检查
    runtime: nvidia
    networks:
      - custom-network

  nbchat-kb-ocr-3:
    image: 192.168.10.155:7777/nbchat_build_release/nbchat-kb-ocr:2.0
    container_name: nbchat-kb-ocr-3
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    ports:
      - 28083:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/8080'"]
      interval: 5s         # 每 5 秒检测一次
      timeout: 3s          # 检查超时 3 秒
      retries: 5           # 连续 5 次失败才标记为 unhealthy
      start_period: 60s    # 容器启动后等待 10 秒再开始健康检查
    runtime: nvidia
    networks:
      - custom-network

  nbchat-kb-ocr-4:
    image: 192.168.10.155:7777/nbchat_build_release/nbchat-kb-ocr:2.0
    container_name: nbchat-kb-ocr-4
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    ports:
      - 28084:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/8080'"]
      interval: 5s         # 每 5 秒检测一次
      timeout: 3s          # 检查超时 3 秒
      retries: 5           # 连续 5 次失败才标记为 unhealthy
      start_period: 60s    # 容器启动后等待 10 秒再开始健康检查
    runtime: nvidia
    networks:
      - custom-network

# 创建网络
networks:
  custom-network:
    driver: bridge